'use client';

import { useCallback } from 'react';
import { Destination, UserPreferences, MONTH_NAMES, MONTHS_ORDERED } from '@/types';
import { formatDuration } from '@/lib/utils';
import { RetroButton } from '@/components/ui/RetroButton';
import { useToast } from '@/hooks/useToast';

interface PrintButtonProps {
  destination: Destination;
  preferences: UserPreferences;
  className?: string;
}

export function PrintButton({ destination, preferences, className }: PrintButtonProps) {
  const toast = useToast();

  const handlePrint = useCallback(() => {
    toast.info('Opening print dialog...');
    setTimeout(() => {
      window.print();
    }, 100);
  }, [toast]);

  return (
    <button
      onClick={handlePrint}
      className={`px-3 py-1.5 font-mono text-xs uppercase tracking-wider rounded
        border border-text-muted/50 text-text-secondary
        hover:border-retro-cyan hover:text-retro-cyan transition-all ${className}`}
      aria-label={`Print ${destination.name} details`}
    >
      <span className="flex items-center gap-1.5">
        <span>🖨️</span>
        <span>Print</span>
      </span>
    </button>
  );
}

// This component renders only during print
export function PrintableContent({
  destination,
  preferences,
}: {
  destination: Destination;
  preferences: UserPreferences;
}) {
  const bestMonths = MONTHS_ORDERED.filter(m => destination.bestMonths[m] >= 8);

  return (
    <div className="print-only hidden print:block p-8 bg-white text-black">
      {/* Header */}
      <div className="mb-8 border-b-2 border-black pb-4">
        <h1 className="text-3xl font-bold mb-2">{destination.name}</h1>
        <p className="text-lg text-gray-600">{destination.countries.join(', ')}</p>
        {destination.region && (
          <p className="text-sm text-gray-500">{destination.region}</p>
        )}
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-4 gap-4 mb-8">
        <div className="border p-3 rounded">
          <div className="text-sm text-gray-500">Duration</div>
          <div className="text-lg font-bold">{formatDuration(destination.duration)}</div>
        </div>
        <div className="border p-3 rounded">
          <div className="text-sm text-gray-500">Climate</div>
          <div className="text-lg font-bold">{destination.climate}</div>
        </div>
        <div className="border p-3 rounded">
          <div className="text-sm text-gray-500">Type</div>
          <div className="text-lg font-bold">{destination.type}</div>
        </div>
        <div className="border p-3 rounded">
          <div className="text-sm text-gray-500">Cost Level</div>
          <div className="text-lg font-bold">{'$'.repeat(Math.ceil(destination.cost / 2))}</div>
        </div>
      </div>

      {/* Best Months */}
      <div className="mb-8">
        <h2 className="text-xl font-bold mb-2">Best Time to Visit</h2>
        <p className="mb-2">{destination.bestTimeDescription}</p>
        <p className="text-sm">
          <strong>Best months:</strong>{' '}
          {bestMonths.map(m => MONTH_NAMES[m]).join(', ')}
        </p>
      </div>

      {/* Itinerary */}
      <div className="mb-8">
        <h2 className="text-xl font-bold mb-2">Itinerary Summary</h2>
        <p>{destination.itinerarySummary}</p>
      </div>

      {/* Considerations */}
      <div className="mb-8">
        <h2 className="text-xl font-bold mb-2">Important Considerations</h2>
        <p>{destination.considerations}</p>
      </div>

      {/* Visa */}
      <div className="mb-8">
        <h2 className="text-xl font-bold mb-2">Visa Requirements</h2>
        <p>{destination.visaRequirements}</p>
      </div>

      {/* Footer */}
      <div className="mt-12 pt-4 border-t text-sm text-gray-500">
        <p>Generated by Travel Agent Zero • {new Date().toLocaleDateString()}</p>
        <p>Travel month: {MONTH_NAMES[preferences.travelMonth]}</p>
      </div>
    </div>
  );
}
